#spring:
#  datasource:
#    username:root
#      password:sandara@123
#        url:jdbc:mysql://localhost:3306/app
#          driver-class-name:com.mysql.cj.jdbc.Driver
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
